import { db } from "../db";
import type { OccupantSpec } from "./occupants-ctx";

// Phase 2 pinned people. unit_id is generated by insertUnit — resolve by unit_number.
// Consideration = that unit's existing base_price_inr (do not invent SOP numbers).

export interface Phase2Person {
  unit_number: string;
  booking_id: string;
  booking_number: string;
  customer_id: string;
  applicant_id: string;
  name: string;
  phone: string;
  pan: string;
  demand_ids: string[];
}

export const ADITI: Phase2Person = {
  unit_number: "MV-01", booking_id: "b_mv01", booking_number: "BK-MV01",
  customer_id: "c_aditi", applicant_id: "a_mv01", name: "Aditi Bansal",
  phone: "9845088801", pan: "ADITB1234A", demand_ids: [],
};
export const HARISH: Phase2Person = {
  unit_number: "MV-02", booking_id: "b_mv02", booking_number: "BK-MV02",
  customer_id: "c_harish", applicant_id: "a_mv02", name: "Harish Patel",
  phone: "9845088802", pan: "HARIS1234P", demand_ids: [],
};
export const NISHA: Phase2Person = {
  unit_number: "MT1-201", booking_id: "b_mt201", booking_number: "BK-MT201",
  customer_id: "c_nisha", applicant_id: "a_mt201", name: "Nisha Verma",
  phone: "9845088803", pan: "NISHA1234V",
  demand_ids: ["d_mt201_1", "d_mt201_2", "d_mt201_3", "d_mt201_4", "d_mt201_5"],
};
export const SURESH: Phase2Person = {
  unit_number: "MP-01", booking_id: "b_mp01", booking_number: "BK-MP01",
  customer_id: "c_suresh", applicant_id: "a_mp01", name: "Suresh Naik",
  phone: "9845088804", pan: "SUREN9012K",
  demand_ids: ["d_mp01_1", "d_mp01_2", "d_mp01_3", "d_mp01_4", "d_mp01_5"],
};

export const TANVI = { name: "Tanvi Joshi", phone: "9845088805", email: "tanvi@example.com" as const };

export async function resolveMeadowsOccupant(p: Phase2Person): Promise<OccupantSpec> {
  const r = await db.query<{ id: string; base_price_inr: string | number }>(
    `SELECT id, base_price_inr FROM unit WHERE unit_number = $1`,
    [p.unit_number]
  );
  if (!r.rows[0]) throw new Error(`seed: unit ${p.unit_number} not found`);
  return {
    unit_id: r.rows[0].id,
    booking_id: p.booking_id,
    booking_number: p.booking_number,
    customer_id: p.customer_id,
    applicant_id: p.applicant_id,
    name: p.name,
    phone: p.phone,
    pan: p.pan,
    consideration: Number(r.rows[0].base_price_inr),
    demand_ids: p.demand_ids,
  };
}
