"""DEPRECATED (TASKS Vivek 7). v1's GridFS blob store behind the attachment routes.

Replaced by `kernel/files/` — `POST /api/v1/files/presign` -> browser PUT -> confirm ->
302 to a presigned GET, with `file_object` rows in Postgres (technical/08 §1). These
routes are kept only so the v1 Mongo routers keep working under `HOMEFLOW_V1_MONGO=1`,
and they still read and write Mongo, not S3: v1 attachment ids, the `attachments`
collection and its verification workflow have no counterpart in `file_object` yet, so
re-pointing them at S3 is the Mongo->Postgres cutover (TASKS Vivek 16), not a small
change. Delete this file with the last v1 router that references an attachment.
"""
from __future__ import annotations

import uuid
from typing import Any, Optional

from fastapi import HTTPException, UploadFile
from motor.motor_asyncio import AsyncIOMotorGridOut

from kernel.mongo import get_gridfs_bucket


async def save_upload_stream(
    file: UploadFile,
    *,
    max_bytes: int,
    filename: str,
    content_type: str,
    metadata: dict[str, Any] | None = None,
    chunk_bytes: int = 1024 * 512,
) -> tuple[str, int]:
    """Stream an ``UploadFile`` into GridFS with an enforced byte cap.

    Raises ``HTTPException(413)`` when ``max_bytes`` is exceeded; the
    partially-written GridFS entry is cleaned up before raising so we
    never leave orphaned chunks.
    """
    bucket = get_gridfs_bucket()
    file_id = uuid.uuid4().hex  # string _id — no BSON<->str coercion in app code
    meta = dict(metadata or {})
    meta.setdefault("content_type", content_type)
    stream = bucket.open_upload_stream_with_id(
        file_id=file_id,
        filename=filename,
        metadata=meta,
    )
    size = 0
    try:
        while True:
            chunk = await file.read(chunk_bytes)
            if not chunk:
                break
            size += len(chunk)
            if size > max_bytes:
                # Abort: closes and deletes the partial file.
                try:
                    await stream.abort()
                except Exception:
                    pass
                raise HTTPException(
                    status_code=413,
                    detail=f"File exceeds {max_bytes // (1024 * 1024)} MB limit",
                )
            await stream.write(chunk)
        await stream.close()
    except HTTPException:
        raise
    except Exception:
        try:
            await stream.abort()
        except Exception:
            pass
        raise
    finally:
        try:
            await file.close()
        except Exception:
            pass
    return file_id, size


async def save_bytes(
    data: bytes,
    *,
    filename: str,
    content_type: str,
    metadata: dict[str, Any] | None = None,
) -> str:
    """Store a pre-generated byte-string in GridFS. Returns the new file id."""
    bucket = get_gridfs_bucket()
    file_id = uuid.uuid4().hex
    meta = dict(metadata or {})
    meta.setdefault("content_type", content_type)
    await bucket.upload_from_stream_with_id(
        file_id=file_id,
        filename=filename,
        source=data,
        metadata=meta,
    )
    return file_id


async def open_download_stream(gridfs_file_id: str) -> Optional[AsyncIOMotorGridOut]:
    """Return an open download stream, or ``None`` if the blob is missing."""
    if not gridfs_file_id:
        return None
    bucket = get_gridfs_bucket()
    try:
        return await bucket.open_download_stream(gridfs_file_id)
    except Exception:
        # gridfs.NoFile is raised when the id doesn't exist — treat any read
        # failure as "missing" and let the caller mark the doc file_missing.
        return None


async def delete_attachment(gridfs_file_id: str) -> bool:
    """Best-effort delete. Returns ``True`` on success."""
    if not gridfs_file_id:
        return False
    bucket = get_gridfs_bucket()
    try:
        await bucket.delete(gridfs_file_id)
        return True
    except Exception:
        return False
